### ISSUE TITLE
UTM/MGRS for polar coordinates.

### ISSUE THREAD

**Issue by FalcoGer** [Tronald/CoordinateSharp#100]
**Is your feature request related to a problem? Please describe.**
Currently UTM grids A/B and Y/Z are deemed invalid.

**Describe the solution you'd like**
UTM grids A/B and Y/Z should reflect the polar regions as described in UTM/MGRS specs.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Tronald** [comment]
This one can be a bit confusing. The UTM system doesn’t work well with circumpolar regions, which is why many UTM tools leave off those lat zones. The Universal Polar Stereographic (UPS) which is a compliment of UTM should be used in those regions as far as I understand.

It acts like an extension of UTM to handle those regions once entered. It’s something I have thought about including in the library, but a need hasn’t been expressed for it yet, as most people aren’t needing conversion in those areas.

I will keep it in mind however, or if someone wants to attack this they are more then welcome.

If someone wishes to work this...

I would like to create a separate class and handle as a separate property within the coordinate (apart from the UTM property). If somebody wishes to work the conversion to/from Lat/Long logic I can plug it into the library.

**Comment by Tronald** [comment]
Closing and adding to enhancement tracker

**Comment by Tronald** [comment]
Hi @FalcoGer 

This is going to be added for the next release. We aren't sure if MGRS conversion will be included yet, but UTM will auto convert to UPS for the polar regions with no performance hit.

Removing from enhancement tracker and reopening issue.

**Comment by Tronald** [comment]
I spoke too soon on the MGRS Polar Coordinates. Those should make it in as well :)

**Comment by Tronald** [comment]
Released with 2.4.1.1

Reference [new issue](https://github.com/Tronald/CoordinateSharp/issues/123) regarding precision.
