### ISSUE TITLE
Transformations between ECEF and ENU coordinates 

### ISSUE THREAD

**Issue by ahold9** [Tronald/CoordinateSharp#101]
first of all, thank you for sharing your project!

I would appreciate the following feature:

- I would like to transform WGS84/ECEF Coordinates to a local cartesian coordinate system, with given origin like described on the following page (preferred would be NED):
- []https://en.wikipedia.org/wiki/Local_tangent_plane_coordinates

**Comment by Tronald** [comment]
Thank you for checking out CoordinateSharp, your suggestion and providing a reference.

Because the system requested is a Cartesian and NED can be simply converted from ECEF, this shouldn’t be too difficult to implement. I will probably extend The ECEF logic to handle the conversion much like MGRS is extended from UTM. 

The only downside of doing it this way is the coordinate systems EagerLoading option would be tied to ECEF, but conversions to ECEF are very inexpensive. I will research this and determine and implementation timeline.

**Comment by Tronald** [comment]
* Added to [Enhancement Requests](https://github.com/Tronald/CoordinateSharp/blob/master/ENHANCEMENT%20REQUESTS.md)
