### ISSUE TITLE
Longitudinal positions cannot be set to North or South

### ISSUE THREAD

**Issue by det-iot** [Tronald/CoordinateSharp#107]
Hello,

I have an app in which I used the current stable version 1.1.5.2 with the following code:

```
var c = new Coordinate();
            c.Latitude = new CoordinatePart((int)latgrados, (int)latminutos, latsegundos, ((flags & 0x02) > 0) ? CoordinatesPosition.S : CoordinatesPosition.N, c);
            c.Longitude = new CoordinatePart((int)longrados, (int)lonminutos, lonsegundos, ((flags & 0x04) > 0) ? CoordinatesPosition.W : CoordinatesPosition.E, c);
```

All work well even when the CoordinatePart(int, int, double, cordinatesPosition, coordinate) show an message advertising is deprecated.

If I try to use the version. 2.1.1.1-beta.2 (also with version 1.1.5.2) with the following code:

```
var cp = new CoordinatesPosition();
c.Latitude = new CoordinatePart((int)latgrados, (int)latminutos, latsegundos,  cp);
c.Longitude = new CoordinatePart((int)longrados, (int)lonminutos, lonsegundos, cp);
```
 I have the following error:

> Longitudinal positions cannot be set to North or South

Is there something wrong in my code?

 
           

**Environment:**
 - .NET Core 2.2
 - CoordinateSharp version. 2.1.1.1-beta.2
 - Console App
 - Is mutlithreading being used? Yes

**Comment by Tronald** [comment]
Hi There, Thanks for checking out CoordinateSharp

So it looks like you aren't setting the `CoordinatePosition` in your second example. You create the variable, but don't assign it a value you so it is most likely defaulting to "Latitude". Because you don't ever change the value, it thinks you are trying to set a longitude with a latitudinal coordinate part. I would remove the 'cp' variable all together and use static flags.

For example change this

```C#
var cp = new CoordinatesPosition();
c.Latitude = new CoordinatePart((int)latgrados, (int)latminutos, latsegundos,  cp);
c.Longitude = new CoordinatePart((int)longrados, (int)lonminutos, lonsegundos, cp);
```

to this 

```C#
c.Latitude = new CoordinatePart((int)latgrados, (int)latminutos, latsegundos,  CoordinatePart.Latitude);
c.Longitude = new CoordinatePart((int)longrados, (int)lonminutos, lonsegundos, CoordinatePart.Longitude);
```

The CoordinatePart class is meant to be very dynamic, which is why you have to tell it if it's a Lat or Long when it's built. Let me know if that fixes your issue and I will close this :)

-Justin

**Comment by Tronald** [comment]
Lastly, if you need the variable `CoordinatesPart` just make sure you set it. 

Example:

```C#
var cp = CoordinatesPosition.N;
c.Latitude = new CoordinatePart((int)latgrados, (int)latminutos, latsegundos,  cp);
cp = CoordinatesPosition.E;
c.Longitude = new CoordinatePart((int)longrados, (int)lonminutos, lonsegundos, cp);
```

You should also note that setting the CoordinatePart's individually is expensive. If the expense effects you let me know and I can help you with efficiency. That is totally application dependent though.

**Comment by det-iot** [comment]
Thank you Tronald. I will change it in my code.

I will also test about the cost performance you mentioned it.
