### ISSUE TITLE
UTM / MGRS Parser Format Addition

### ISSUE THREAD

**Issue by Tronald** [Tronald/CoordinateSharp#109]
Failed parse logs taken from the CoordinateSharp website consistently show users attempting to parse UTM/MGRS coordinates in a single string with no spaces.

For example:

MGRS Coordinate "10S GJ 06832 44683" may be passed as "10SGJ0683244683". The parser will fail in this format.

The following regex formula can be used to match strings in the format.

[0-9]{1,2}[a-z,A-Z]{3}\d+

If a match occurs, we can break down the string into the appropriate coordinate sections. 

The parser should still fail if the northing/easting character count is not an even number as it signals a different precision for each coordinate part. The combined northing/easting characters will be split at the halfway count and parsed as strings into doubles. 

This is planned to be updated with v2.1.1.2

**Comment by Tronald** [comment]
MGRS Formats in which the Lat and Long Zones are combined into a string are parsing incorrectly. The bug will be fixed with v2.2.1.1 in addition to the parser improvement.

**Comment by Tronald** [comment]
Fixed and improved with v2.2.1.1

**Comment by vishnu4** [comment]
Can i ask how/where we can use this?  I often get MGRS results in either format, like 10S GJ 06832 44683 or 10SGJ0683244683, and would like to be able to feed it into the MilitaryGridReferenceSystem class to get a valid object out of it.  but according to https://coordinatesharp.com/DeveloperGuide#universal-transverse-mercator-and-military-grid-reference-system , it seems like i need to parse the object out myself in order to fit your constructor.

Are there plans on being able to initialize the object like 
`MilitaryGridReferenceSystem mgrs = new MilitaryGridReferenceSystem(mgrsString);`
in the future?

**Comment by Tronald** [comment]
Hi There @vishnu4 

All parsing is done using `Coordinate.TryParse()`. So to get the `MilitaryGridReferenceSystem` object from a string, you would do the following.

```C#
string mgrsString = "10SGJ0683244683";
Coordinate coord;

//Attempt to parse the string to create a populated Coordinate object
Coordinate.TryParse(mgrsString, out coord);

//Extract the MilitaryGridReferenceSystem object from the Coordinate
MilitaryGridReferenceSystem mgrs = coord.MGRS;
```

With that said, string constructors for UTM and MGRS is probably a good idea to have. I will make note if this a new feature.

Let me know if you have anymore questions.
