### ISSUE TITLE
how to convert from epsg to lat long (utm) vice versa

### ISSUE THREAD

**Issue by iotble** [Tronald/CoordinateSharp#120]
Is it possible to convert coordinates by using EPSG code to Lat Long or UTM and vice versa?
if yes, it will be helpful to have some sample code snippet for this. 

thanks in advance

**Comment by Tronald** [comment]
Hi there,

Unfortunately CoordinateSharp doesn’t have the ability to convert to EPSG, and probably never will. The library is designed to be a self contained math based solution to coordinate conversions. Since the EPSG projection system relies upon map data (as far as I know I could be wrong), it’s outside the intended scope of the library.

Sorry for the bad news 😢
