### ISSUE TITLE
Coordinate.TryParse() efficiency issues [QUESTION]

### ISSUE THREAD

**Issue by mohammad4x** [Tronald/CoordinateSharp#126]
Hi. I'm using CoordinateSharp to parse and validate my input locations from users. inputs are in two different formats like "55.066464133, 66.354123569" and "55° 3' 52.146'' N 66° 39' 17.3628'' E". I use CoordinateSharp just for validating and generating the "lat, lon" string of it. The "TryParse" method takes too long to run (60ms). is there a way to achieve this in much lower time? below is my code:

```
        private long GetLocation(IEnumerable<string> inputLocations)
        {
            var result = new List<string>();

            foreach (var location in inputLocations)
            {
                if (Coordinate.TryParse(location, out var parsedLocation))
                    result.Add($"{parsedLocation.Latitude.ToDouble()},{parsedLocation.Longitude.ToDouble()}");
            }
        }
```

**Comment by mohammad4x** [comment]
I found the solution for this problem. it was "EagerLoad" option that was slowing down making new objects of "Coordinate" class. i added the overload methods for "TryParse" with EagerLoad option as parameter for performance issues and made the fork for it.

**Comment by Tronald** [comment]
Thank you raising this issue.

Parsing wasn't built with bulk conversions in mind, but I 100% agree that this option should be available as it would increase conversion efficiency greatly.

I do have a couple of questions however as the benchmark you listed concerns me.

1. What version of CoordinateSharp are you using?

2. What are the specs of the machine running the code? I find the **60ms** benchmark time odd as it only takes about 6 seconds for a single geodetic coordinate string to parse (_benchmarked on a i7-8550U 1.80GHz 1.99 GHz (x64)_). A less powerful processor would certainly increase the benchmark, but 60 seconds is a 10x increase to the benchmark which seems unusually large to me. 

Parsing occurs with all eager loading off, but it reactivates as soon as the coordinate successfully parses and fires off all conversions 1 time. Because of this, geodetic coordinates that are parsed should be hitting almost the same benchmark as standard instantiated `Coordinate` object.

I would like to investigate this further if your benchmarks are that slow.

Leaving this issue open until the feature is added (next release). I'm going to comment on your Pull Request next.

Thank you again.

**Comment by mohammad4x** [comment]
1- I'm currently using 2.3.1.1v.
2- I've got the 60ms on TryParse method (and also on manually instantiation a coordinate object with default EagerLoad option) on a i5-4460@3.20GHz (x64) desktop processor.

As i mentioned in the question, I use CoordinateSharp just for validating the input string and maybe one or two Geo-type conversion but i needed it to be as fast as possible. I didn't use the EagerLoad option and it was slowing me down.

Thank you for your response

**Comment by Tronald** [comment]
Thank you for the info @mohammad4x

**Comment by Tronald** [comment]
`EagerLoad` overloads have been added to all `Coordinate.TryParse()` methods and committed to the [develop branch](https://github.com/Tronald/CoordinateSharp/tree/develop).

Benchmarks have been reduced to < 1ms with all `EagerLoad` options turned off when parsing a geodetic string.

This feature will go out with the next release (approximately 1-2 weeks).

Leaving the issue open for reference until release of 2.4.3.1.

Thank you for the great suggestion!

**Comment by mohammad4x** [comment]
Thank you for your effort :)

**Comment by Tronald** [comment]
v2.4.3.1 Released

Example Usage:

```C#
//Create EagerLoad object with multiple flags
EagerLoad el = new EagerLoad(EagerLoadType.ECEF);

//Parse string to coordinate with eager loading settings specified.
Coordinate coord;
Coordinate.TryParse("45.34, 65.47", el, out coord);

```
