### ISSUE TITLE
Sunset calculation goes wrong

### ISSUE THREAD

**Issue by rsteenks** [Tronald/CoordinateSharp#141]
**Describe the bug**
Calculation of certain sunset times doesn't deliver the correct time.

**To Reproduce**
Using gps-coordinates Latitude 43.18000 Longitude -79.46000 and date 04/14/2020 returns a NULL datetime for the sunset when the Celestial.CalculateSunData(latitude, longitude, date) method is used. 

**Expected behavior**
The expected result is the correct sunset-datetime, which can be viewed at https://www.esrl.noaa.gov/gmd/grad/solcalc/table.php?lat=43.18&lon=-79.46&year=2020

**Environment (please complete the following information):**
 - .NET version. 4.6.2
 - CoordinateSharp version. 2.5.1.1 (Also tried 2.6.1.1 with same result)
 - Application type. Windows-service
 - Is mutlithreading being used? No

**Additional context**

**Comment by Tronald** [comment]
Thanks for Checking out CoordinateSharp

The problem you are facing is common and people run into it often due to a misunderstanding of how CoordinateSharp returns celestial values. The library returns solar/lunar times on a "Per Day" basis not a "Last/Next" basis.

Considering that fact, we must remember that in the spring, solar cycles are slightly greater than 24 hours. As you are working in UTC time, the location and date provided does not actually have a sunset that occurs on the 14th (it occurs seconds after midnight UTC on the 15th). 

You have a few options to handle this per the [Developer Guide](https://coordinatesharp.com/DeveloperGuide#checking-celestial-body-conditions)

**Method 1: Check Celestial Conditions**

You should always check for null values of any property that has a nullable `DateTime` like `Sunset`.

```c#
if(!coordinate.Celestial.Sunset.HasValue)
{
      c.CelestialInfo.SunCondition; //Outputs "NoSet" to let you know a sunset has not occurred on this day
}
else
{
      //You methods run here
}
```

**Method 2: Operate in LOCAL time**

```c#
//Change UTC offset of Coordinate object to specify local time operation.
//You are responsible for daylight saving adjustments
coordinate.Offset = -4;
```

**Method 2: Use Last/Next event methods (static only)**

```c#
//Will always return a datetime.
//This method is a slower in polar regions as it will have to iterate each day until a value is found.
DateTime d = new DateTime(2019, 2, 6);
DateTime val = Celestial.Get_Next_SunRise(40.0352, -74.5844, d);    
```

Please reach out if you have anymore questions.

**Comment by rsteenks** [comment]
Hello Justin,

Thanks for your explanation.

I've updated my code and everything works as expected now.

Best regards,
Richard Steenks


Op di 9 jun. 2020 om 18:29 schreef Justin Gielski <notifications@github.com
