### ISSUE TITLE
Incorrect MGRS Northing & Easting Parsing when accuracy below 1 Meter

### ISSUE THREAD

**Issue by cvergaray** [Tronald/CoordinateSharp#142]
**Description of bug**
When parsing an MGRS string where the easting & northing are less than 10 digits, i.e. accuracy less than 1 meter, the digits should be padded to the right with zeros first. Once parsed, the coordinate should point to the south-western corner of the square. If the easting and northing strings are not padded on the right with zeros, then the parsed coordinate would be closer to the northeastern corner of the square.

For example "16REU 67" should be equivalent to "16REU 60000 70000" not "16REU 00006 00007"

**To Reproduce**
Here is an NUnit3 test that illustrates what I am seeing/expecting:
```
[Test]
public void MgrsParsesConsideringTruncation()
{
    var imprecise = CoordinateSharp.Coordinate.Parse("16REU67");
    var preciseCorrect = CoordinateSharp.Coordinate.Parse("16REU6000070000");
    var preciseIncorrect = CoordinateSharp.Coordinate.Parse("16REU0000600007");

    Assert.Multiple(() =>
    {
        Assert.That(imprecise.Get_Distance_From_Coordinate(preciseCorrect).Meters, Is.EqualTo(0.0));
        Assert.That(imprecise.Get_Distance_From_Coordinate(preciseIncorrect).Meters, Is.Not.EqualTo(0.0));
    });
}
```

**Environment:**
 - .NET version: Standard 2.0
 - CoordinateSharp version: 2.6.1.1
 - Application type: Xamarin Mobile Application (iOS, Android, & UWP) for Military response operations
 - Is mutlithreading being used: Yes

**Additional context**
We have been able to get around this in the past by simply adding the padding when parsing the string, i.e.:
```
int.TryParse(east.PadRight(5, '0'), out easting)
int.TryParse(north.PadRight(5, '0'), out northing)
```

**Comment by Tronald** [comment]
Great catch! That is a major design flaw in the parser and I'm honestly amazed it's taken this long to present. At its current design it should have been set to fail if the 10 digit number was not met, but it only fails if the concocted Northing/Easting is not an even character count (as the program would not be able to determine where Northing ends and Easting begins). Padding a less precise number would be a far better option instead of failing the parser though. It would also be very easy to implement (as shown in your example).

Thank you for pointing this out. I will get this fixed.

**Comment by Tronald** [comment]
Pushing the update now, should be available within the next hour. Thanks again for bringing this up.

**Comment by cvergaray** [comment]
Thank you so much for such a quick response! 
My company is excited to be able to use Coordinate Sharp and this bug was the only thing holding us back. This tool will be a perfect replacement for our old homegrown one.
