### ISSUE TITLE
 Solstice and Equinox

### ISSUE THREAD

**Issue by FloffyTheGreat** [Tronald/CoordinateSharp#144]
I would be great if CoordinateSharp could calculate Solstice and Equinox

**Comment by Tronald** [comment]
Thank you for the great suggestion.

After a bit of research, it would be best to use approximation algorithms (Meeus) to obtain equinox and solstice values. This would keep overhead small, but still give a comfortable accuracy level for most uses intended for the library. Approximation algorithms will eliminate the need to run iterations which would increase algorithm benchmarks by 3 times.

Approximation's largest error margin between 1950-2050 is about 51 seconds.

This will be approached using  "Last/Next Solstice/Equinox" properties from the specified `Celestial` object. 

Once benchmarks are determined an eager loading approach will be specified.

**Comment by Tronald** [comment]
`Solar_Cycle` eager loaded calculations remain under a 1 ms benchmark when solstice and equinox calculations are included. As performance cost is negligible, I am comfortable adding the values to the eager loaded solar cycle properties.

A slight change from the plan above: Instead of "Last/Next", the value will be "current" based on the provided year.

Example:

`Coordinate.CelestialInfo.Solstices.Summer` or `Celestial.Soltices.Summer`

This will be available with the next release.

**Comment by Tronald** [comment]
This has been added to 2.7.1.1 (Released on 7/12/2020)

```C#
Coordinate c = new Coordinate(45,112, new DateTime(2020,3,6));
Console.WriteLine(c.CelestialInfo.Solstices.Summer);//20-Jun-2020 21:44 (UTC)
Console.WriteLine(c.CelestialInfo.Equinoxes.Spring);//20-Mar-2020 03:51 (UTC)
```

Eager loading extensions were also added last minute. Performance hits were negligible, but we wanted the option to turn the new feature off as lower powered processors may need to maximize performance where able. We didn't want to force users to take the hit. Values are eager loaded by default however.

To turn off calculations application wide.

```C#
//Set this in the application startup logic
 GlobalSettings.Default_EagerLoad.Extensions.Solstice_Equinox = false;
```

Note: `Solstices` and `Equinoxes` Properties will still be created with empty values when eager loading is off. This equates to an approximate 424 bytes in memory.
