### ISSUE TITLE
SunAltitude vs Astronomical dark (and some more questions)

### ISSUE THREAD

**Issue by Pydis123** [Tronald/CoordinateSharp#149]
First of all: awesome package you got going here, I've been looking for something like this for some time.

Question: I'm trying to figure out how to determine when it's astronomical dark, that is when the sun is 18 degrees below the horizon.
However, looking at "SunAltitude" I can't figure out how to interpret that value and translate it into degrees.
Can you explain this value to me, or explain how I can figure it out otherwise?

Bonus question: IsMoonUp/IsSunUp, How is those bools determined? Is it true when the sun is x degrees below the horizon?

**Comment by Tronald** [comment]
Thanks for checking out CoordinateSharp and your kind words.

Regarding Astronomical "darks", you can get those times from the `AdditionalSolarTimes` property within the `Celestial` class. You shouldn't even need to translate those from the solar altitude (unless you just want to). These times register when the solar altitude hits 18 degrees below horizon as you stated. 

```c#
//Seattle, Washington on 2020/7/7 @ 02:00 AM
Coordinate c = new Coordinate(47.6062095,-122.3320708,new DateTime(2020,7,10,2,30,0));
		
//Change UTC offset to run in local time
c.Offset=-7;
						
Console.WriteLine(c.CelestialInfo.AdditionalSolarTimes.AstronomicalDawn); //02:35
Console.WriteLine(c.CelestialInfo.AdditionalSolarTimes.AstronomicalDusk); //23:56
```

The solar altitude should already be translated into degrees for you. Taking the values from the above example:

```c#
Console.WriteLine(c.CelestialInfo.SunAltitude); //-18.2 degrees @ 2:30 AM (Nearing Astronomical Dawn Event)
```
I always like to note that these formulas are based on estimated math algorithms. They do not account for altitude, current refraction, almanac data, etc.  Because of this you will see variations in event times, but accuracy is sufficient for most cases.

Another really important note is that Dusk/Dawn events do not always occur (depending on time of year and location). These date times are `nullable` and must be handled as such. 

Lastly, CoordinateSharp works on a "per-day" basis, not a last/next event basis. Because of this you may see dusks occur before dawn / or non events when working in UTC time (even though one occurs in local). This is described in the [developer guide](https://coordinatesharp.com/DeveloperGuide#checking-if-celestial-body-is-up). So if you see a variations when comparing data of a few minutes, look to see if the compared service is actually using "last/next" event logic.

The `IsSunUp` / `IsMoonUp` values are determined simply by taking the user provided `DateTime` and comparing them the the `Celestial` Rise/Set events as well as the `SunCondition` `MoonCondition` Properties. The logic is fairly simple and can be viewed [here](https://github.com/Tronald/CoordinateSharp/blob/afaac6ab70fb41d3df6cc407c0c14c0d5421ce87/CoordinateSharp/Celestial/Celestial.StaticMethods.cs#L254).

On a final note, you may want to have a look at modifying the `EagerLoading` settings if you plan to only work with solar times. It can greatly improve performance. [Performance Tips](https://coordinatesharp.com/Performance).

Let me know if that answered your questions and if you need anymore help. I will keep the issue open until you repsond.

**Comment by Pydis123** [comment]
Thanks! I think that solves all my "problems"!

**Comment by Tronald** [comment]
Great to hear! Reach out if you need anymore help.
