### ISSUE TITLE
UTM coordinates

### ISSUE THREAD

**Issue by MaxwellCanton** [Tronald/CoordinateSharp#19]
How to convert a utm coordinate to Lat/Lng coordinate?

**Comment by Tronald** [comment]
UTM/MGRS cannot convert back to lat/long at this time. This feature needs to be added, it just hasn’t been a priority due to demand for celestial additions.

I’m finishing up 1.1.1.6. In the next few days. Let me research this issue and see if it’s something I can quickly include in the release.

If not I will add it to the enhancement request tracker (1.1.1.6 branch).

**Comment by Tronald** [comment]
It got it working with some slight accuracy issues. I had started writing these conversion before, I just never finished them. I am going to release a BETA version of this function with 1.1.1.6. I am going to see how much I can clean it up over the next couple days before I release. I will let you know it's status in a few days.

**Comment by MaxwellCanton** [comment]
Thanks Tronald , you will help me a lot if you do it.

**Comment by Tronald** [comment]
Maxwell I just pushed version 1.1.2.1 (changed from 1.1.1.6 due to some larger than anticipated changes) to Nuget. It may take a bit to index, so give it a while if you don't see it in your search.

The feature you need is described in the documentation, but here is an example of what you need.

```C#
UniversalTransverseMercator utm = new UniversalTransverseMercator("T", 32, 233434, 234234);
Coordinate c = UniversalTransverseMercator.ConvertUTMtoLatLong(utm);
```
Your lat/long values will be contained in your Coordinate object.

If you use NATO UTM, use the` MilitaryGridReference` object instead of the `UniversalTransverMercator`.

If you use a UTM with a Southern/Northern hemisphere format instead of a zone letter format, just throw a "C" in for southern hemisphere and "T" for northern. The formulas will figure out what you mean.

You may refer to documentation for accuracy of conversions. Let me know if you have any issues with it.

**Comment by MaxwellCanton** [comment]
@Tronald thanks you just helped me so much !, Everything is working fine! .

**Comment by Tronald** [comment]
Glad to hear it. Thanks for letting me know 👍
