### ISSUE TITLE
Coordinate.Offset has improper range limitation.

### ISSUE THREAD

**Issue by bp2008** [Tronald/CoordinateSharp#193]
**Describe the bug**

`Coordinate.Offset` refuses to accept a value greater than `12`.  Exception is thrown: "Time offsets cannot be greater than 12 or less than -12."

Locations such as [Kiribati](https://en.wikipedia.org/wiki/Kiribati) have time zone offsets as high as `14`.  [Wikipedia UTC time offsets list](https://en.wikipedia.org/wiki/List_of_UTC_time_offsets#UTC+12:00,_M).

**To Reproduce**
Please provide a reproducible code example if able.
```
Coordinate c = new Coordinate(1.466667, 173.033333, DateTime.Now);
c.Offset = 14;
```

**Expected behavior**
Coordinate Offset accepted range should be `-12` to `14`.

**Environment (please complete the following information):**
 - .NET version.   **.NET Framework 4.5.2**
 - CoordinateSharp version.   **2.11.1.1**
 - Application type.  **Windows Application**
 - Is mutlithreading being used?  **Yes**

**Additional context**

**Comment by Tronald** [comment]
Offset needs +2 hour validation extension. 

Great catch thank you. The initial design was around a 24 clock from UTC midpoint, without consideration to location. Obviously this can cause issues for local time applications.

We will get this patched up quickly.

**Comment by Tronald** [comment]
Patch is built for CoordinateSharp, I just need to button up a few things before I push it (should be on Nuget in the next hour). I want to note a few odd things I noticed about this region though. Most webservices seem to exhibit the same behavior (with +12 UTC offset max).

For example Time and Date says LINT is +14 : https://www.timeanddate.com/time/zones/lint
But their sun times appear in +12:  https://www.timeanddate.com/sun/@4030885

NOAA however seems to exhibit the correct behavior when setting +14 UTC (notice the 2 hour difference in reported time): https://gml.noaa.gov/grad/solcalc/

![image](https://user-images.githubusercontent.com/24424871/134956338-142e83db-b1b5-44f7-ad2f-fe49a105c63f.png)

I bring this up, because testing in this region may require additional research. The math in CoordinateSharp is correct though from testing (adding 14 hours from UTC for solar/lunar calculation).

**Comment by Tronald** [comment]
Patch pushed to [Nuget with v2.12.1.1 ](https://www.nuget.org/packages/CoordinateSharp/)
