### ISSUE TITLE
Bug in the Move-Function with Length+Bearing

### ISSUE THREAD

**Issue by bigkukuban** [Tronald/CoordinateSharp#202]
Distance movement with bearing is not performed correctly. It's about the  Coordinate.Moveove(LENGTH, BEARING (=here 90°), Shape.Ellipsoid);- function.

Try to draw a rectangle on the surface of the earth with a 90° angle.
The result always has shifted sides. 

The cause seems to be a flipping of Lon/Lat. If these are twisted, the result is as expected.

**Comment by Tronald** [comment]
Could you provide a code example that reproduces the issue?

The 100 KM  90° rotation (box) example here does not reproduce the issue you describe:  https://dotnetfiddle.net/GMGywC 

Note: The start location will never equal the end location due to the earths shape. The bearing entered is simply an "initial" bearing and is expected to "shift" over distance. You can expect more shift over a greater distance. This is expected.

Our formulas are adapted from [Ed Williams Great Circle Calculator](http://edwilliams.org/gccalc.htm). His formulas are used by agencies such as [NOAA](https://www.nhc.noaa.gov/gccalc.shtml) and are generally considered accurate as estimates. More info on Great Circle calculation can be [viewed here.](http://edwilliams.org/avform147.htm#Intro).

**Comment by bigkukuban** [comment]
Hi, thank you for the response.

I'm creating an rectangle with 100 m Side Length.

This is my code: 

double width = 100;
double heigth = 100;

var crdInitialPointA = new Coordinate(52.073018535963556, 8.69649589116307);
var crdInitialPointB = new Coordinate(52.073783497352025, 8.695117235729413);            

Distance distanceAB = new Distance(crdInitialPointA, crdInitialPointB, Shape.Ellipsoid);

double baseBearing = distanceAB.Bearing;
double bearingAC = baseBearing - 90.0;
double bearingBD = baseBearing - 90.0;

 //Calculate Punkt B, we start from A
var targetPointB = new Coordinate(crdInitialPointA.Latitude.DecimalDegree, crdInitialPointA.Longitude.DecimalDegree);
targetPointB.Move(heigth, distanceAB.Bearing, Shape.Ellipsoid);

//Calculate Point C, we start with A
var crdInitialPointC = new Coordinate(crdInitialPointA.Latitude.DecimalDegree, crdInitialPointA.Longitude.DecimalDegree);
crdInitialPointC.Move(width, bearingAC, Shape.Ellipsoid);

//Calculate Point D: we start from B
var crdInitialPointD = new Coordinate(targetPointB.Latitude.ToDouble(), targetPointB.Longitude.ToDouble());
crdInitialPointD.Move(width, bearingBD, Shape.Ellipsoid);

String contentFile = "";
contentFile = contentFile + $"{crdInitialPointA.Latitude.DecimalDegree.ToString(CultureInfo.InvariantCulture)},{crdInitialPointA.Longitude.DecimalDegree.ToString(CultureInfo.InvariantCulture)}\n";
contentFile = contentFile + $"{crdInitialPointB.Latitude.DecimalDegree.ToString(CultureInfo.InvariantCulture)},{crdInitialPointB.Longitude.DecimalDegree.ToString(CultureInfo.InvariantCulture)}\n";
contentFile = contentFile + $"{crdInitialPointD.Latitude.DecimalDegree.ToString(CultureInfo.InvariantCulture)},{crdInitialPointD.Longitude.DecimalDegree.ToString(CultureInfo.InvariantCulture)}\n";
contentFile = contentFile + $"{crdInitialPointC.Latitude.DecimalDegree.ToString(CultureInfo.InvariantCulture)},{crdInitialPointC.Longitude.DecimalDegree.ToString(CultureInfo.InvariantCulture)}\n";
contentFile = contentFile + $"{crdInitialPointA.Latitude.DecimalDegree.ToString(CultureInfo.InvariantCulture)},{crdInitialPointA.Longitude.DecimalDegree.ToString(CultureInfo.InvariantCulture)}\n";

------------------
The content of the file is now :
52.073018535963556,8.69649589116307
52.073783497352025,8.695117235729413
52.07295204051025,8.694436151606357
52.072350664535655,8.695519989239664
52.073018535963556,8.69649589116307
-------------------
If we use gmaps/nmea generator/qgis to draw the points on the map, the result is always: 

![Screenshot 2022-09-11 101852](https://user-images.githubusercontent.com/58887074/189518457-7e05ad66-9b02-4940-a663-64dec562bbb1.png)



Conclusion: the angles (even initial) are not 90° and the length of the sides are not as given.
Note: I work on short distances in the meter range.

**Comment by Tronald** [comment]
Thank you for providing the example.

I believe the issue is in your code, but correct me if I am not understanding what you are trying to achieve.

The distance from `crdInitialPointA` to `crdInitialPointB` is 127.202 meters (Confirmed in CoordinateSharp and [geodesyapps](https://geodesyapps.ga.gov.au/vincenty-inverse)). You appear to grab an initial bearing from the returned `Distance` object, and then travel 100 meters using that bearing. You store the result in `targetPointB`, but on your `contentFile` output, you are still using `crdInitialPointB` (which is 127.202 meters distance not 100 like you are attempting to achieve in the code).

Based on your output, it makes sense that you would not have an object resembling a parallelogram if that is your goal. 

Your BA-AC and AC-CD angle appears ~90° as expected, but your other angles are not ~90° which would also be expected based on your output code. You would either need to travel C to D, 127.202 meters to create the rectangle or output `targetPointB` to create a 100m square.

![image](https://user-images.githubusercontent.com/24424871/189538852-de677f10-9a84-4657-8c7a-5a25535e6c68.png)

[A semi working example can be seen here](https://dotnetfiddle.net/cJBmC2). Results are what I believe you are attempting to achieve.

![image](https://user-images.githubusercontent.com/24424871/189539907-45af5f09-0a36-45b1-9ace-b5aebd092991.png)

Let me know if this fixes your problem OR if I am not understanding the problem correctly.

**Comment by bigkukuban** [comment]
Hi, thanks! 

You helped me a lot. The error was in the surrending usage of your lilbary. 
It seemed to me that the reason was somewhere in your library. 
You do a great work.

**Comment by Tronald** [comment]
@bigkukuban thank you for the update. I am glad you opened this issue as it alerted me to the fact that the `Coordinate.Move()` examples have been mistakenly removed from our developer guide. We will update that here soon for clarity.

Reach out if you need any more help!
