### ISSUE TITLE
CalculateCelestialTimes, some date-problems

### ISSUE THREAD

**Issue by lindsoe** [Tronald/CoordinateSharp#223]
For the year 100 and 200 the following line gives a  System.ArgumentOutOfRangeException error for all dates between beginning of february to beginning of may.. Is this a limitation in DateTime or Coordinatesharp?           

Celestial cel = Celestial.CalculateCelestialTimes(39, -72, new DateTime(200,4, 21, 10, 10, 12));

**Comment by Tronald** [comment]
Wow, incredibly fascinating find (looks like you discover a classic leap year bug). This appears to be an actual limitation experienced in the Julian Day math calculations (that almost everyone uses). The bug is appearing during the Lunar Perigee / Apogee Logic in CoordinateSharp. During this calculation, multiple Julian days are iterated for calculation.

One of those Julian days is: 1757641.9447567516 and 1757642.9447567516 

If you drop that day into a "Julian to Gregorian Date" converter it outputs 29-FEB-100....That is not a real date so .NET doesn't like it.

NASA's Jet Propulsion Lab exhibits the save behavior. Enter the first Julian day number above into this tool and you'll see it return the non existent date.  

https://ssd.jpl.nasa.gov/tools/jdc/#/jd

Some tools trigger on the second number (most likely rounding logic differences).

I'll place a catch in there and increment the date up if this occurs. 

Thanks for alerting us.

**Comment by Tronald** [comment]
Researched this a bit further.

Identified limitations exist in the pre Gregorian era (prior to 1582) due to differences between Julian Leap Years and Gregorian Leap Years. This was known, but poorly documented. We are going to put a handler in the Julian to Gregorian date converter to prevent exceptions and document this a bit better.

As such, accuracy is most likely degraded that far back. If you are doing historical research with a tight delta, you may want to reconsider your usage of this library.

**Comment by lindsoe** [comment]
Thanks for response and for looking into the issue. I noticed the exception also is raised for dates between febr. 26 and march 3 for year 300..1500 except 400, 800, and 1200, so I guessed it had something to do with leapyear. Thanks again for useful info.

**Comment by Tronald** [comment]
Bug fixed with [2.19.1.1](https://www.nuget.org/packages/CoordinateSharp/2.19.1.1) pushed today. The limitations have been documented (to include the inability to convert in the BC era). Julian dates of "February 29th" that do not exist on the Gregorian calendar will shift to March 1st for safety. This will create the potential for two consecutive Julian dates with  "March 1st" possibilities during conversion, but as this is a .NET limitation (as the `DateTime` class cannot recognize non-Gregorian leap years) it is the best way to work around the issue.

You will see a CAUTION occur in the debugger output window when the correction is triggered. 

Thanks again for making us aware.
