### ISSUE TITLE
UniversalTransverseMercator can be created and used with wrong UTM coordinates

### ISSUE THREAD

**Issue by dennis95stumm** [Tronald/CoordinateSharp#226]
**Describe the bug**
UniversalTransverseMercator can be created and used with wrong UTM coordinates.

**To Reproduce**
- Create a new UniversalTransverseMercator with the public constructor for example with a invalid est value, e.g. 0.
- The object is created with wrong coordinates.

**Expected behavior**
An exception should be thrown instead of "Warn" in order to prevent the use of wrong coordinates. Maybe it should be possible to control the behaviour with a bool flag in the constructor.

**Environment (please complete the following information):**
 - .NET 6
 - CoordinateSharp: 2.19.1.1

**Additional context**
\-

**Comment by Tronald** [comment]
Hello,

This behavior is by design as it allows for "overprojection". That is why you are "warned" vs "blocked". Is you "parse" an overprojected coordinate using `Coordinate.TryParse()`, you will actually see that the UTM overprojection is corrected and placed in the correct zone. 

With that said, I agree that there needs to be a boolean check to detect overprojection when using the constructor. We will get to work on that.

**Comment by Tronald** [comment]
Feature added with 2.20.1.1 released today. Check the `UniversalTransverseMercator.Out_Of_Bounds` bool property. It will trigger if a UTM coordinate is created outside of system specs.

`Out_Of_Bounds` will not trigger if zone locking is used from `Coordinate` OR is parsed from a string due to autocorrection behavior. 

MGRS does not allow this behavior so it was not implemented.
