### ISSUE TITLE
Loss of precision when converting between UTM and WGS back and forth

### ISSUE THREAD

**Issue by cervengoc** [Tronald/CoordinateSharp#229]
Hi,

We receive input data in UTM33 format, while storing it in WGS format in the database. Hence we need to convert the UTM33 values to WGS, and then back when displaying them to the user.

We are struggling with some significant loss of precision, which at first glance probably should not happen in my opinion. Maybe we're doing something wrong.

As an example, we have code such as this one.

```
var northing = 5763616.61290418;
var easting = -603382.328724074;

var coord = UniversalTransverseMercator.ConvertUTMtoLatLong(
    new UniversalTransverseMercator("N", 33, easting, northing));

var lat = coord.Latitude.ToDouble();
var lon = coord.Longitude.ToDouble();

// Convert back

var coord = new CoordinateSharp.Coordinate(point.Y, point.X);
coord.Lock_UTM_MGRS_Zone(33);

var northingAfterConversion = coord.UTM.Northing;
var eastingAfterConversion = coord.UTM.Easting;

// I would expect that at least 1cm precision should be preserved)

northing.Should().BeApproximately(northingAfterConversion, 0.01);
easting.Should().BeApproximately(eastingAfterConversion, 0.01);

```

The asseritions will fail for us, as the difference is quite significant.
- `northingAfterConversion` is `5763616.54513533` (off by `~7 cm`)
- `eastingAfterConversion` is `-603381.519924373` (off by `~80 cm`)

Could you please help with this one? What is causing this issue, and how could we increase the back and forth conversion precision?

**Comment by Tronald** [comment]
Hi @cervengoc 

The most common reason for precision loss is due truncation of grid type coordinates. If I am reading your code right, it appears you are using centimeter precision, which should mitigate this issue so that is good. I am noticing however, that you are utilizing zone locking and greatly over-projecting your coordinate outside of specification standards.

Over-projection will always lead to some form of additional precision loss in most conversion tools (see the ones below) as you are "projecting" on an curvature that s not accurate to the coordinate's region (remember the earth is not a circle). The acceptable level of precision loss caused is essentially up to each individual user. Various conversion tools will yield vastly different results however. 

https://www.earthpoint.us/Convert.aspx
https://www.ngs.noaa.gov/NCAT/

USER PROVIDED UTM: `33N -603382 5763616`
COORDINATESHARP CORRECTION: `30U 657940mE 5646885mN (50.95192 -0.75137)`
NOAA CORRECTION: `30U 657940mE 5646881mN (50.95189 -0.75137)`
EARTHPOINT CORRECTION: `33U 603382mE 5763616mN (52.0135452, 016.5064133)` (interesting result)

Things become "grey area" when working in this manner when you need to do back and forth conversions. Most basic level conversion algorithms between geodetic lat/long and UTM will not account for such region modifications. 

Sorry I don't have better news on this one.
