### ISSUE TITLE
UTM output precision and central meridian

### ISSUE THREAD

**Issue by LeandroCM88** [Tronald/CoordinateSharp#232]
First of all, I'd like to congratulate you for this library.

It's extremely easy to start developing with it and it's been very pleasnt to study and use.

I've been trying with some lat/lon to UTM conversions, in order to get used with datum, ellipsoids and so on,
and, at this time, I'm struggling with to two questions:

1. Is there a way to get the UTM output including the decimal part of it?

2. Please correct-me if I'm wrong, during the planification calc, the central meridian is an very important information,
in order to minimize the error as we get far from the CM. Do we need to set the CM manually or does the library handle this for us?
If it were set manually, how do I change it?

That's all for now. Thank you again for such usefull tool.

**Comment by Tronald** [comment]
Thank you for your kind words and your questions! These are great questions and I would be happy to answer them.

_**Is there a way to get the UTM output including the decimal part of it?**_

Yes, there are a couple ways depending upon what you are trying to achieve. 

1. Use `.ToRoundedString(int precision)` in instead of `ToString()` within the `UniversalTransverseMercator` object. This allows you to specify your string precision for rounding.
2. Access the `UniversalTransverseMercator` `Northing` and `Easting` properties directly.

Option 1 is by far the easier of the two though as it will format everything for you. [Example Here](https://dotnetfiddle.net/Ugy5xf)

**_Please correct-me if I'm wrong, during the planification calc, the central meridian is an very important information,
in order to minimize the error as we get far from the CM. Do we need to set the CM manually or does the library handle this for us? If it were set manually, how do I change it?_**

The central meridian of a zone is easy to determine, and while important during calculation, is more of a static value: `3 + 6.0 * (utmz - 1) - 180;` Changing the central meridian would essentially distort the coordinate. I think you may possibly be confusing central meridian specification with model specification. UTM by default uses the WGS84 ellipsoid, which as of now is the best "overall" shape for worldwide projection. There are more accurate projections per region however if you need better data in a specific area.

CoordinateSharp does allow you to alter the datum of a `Coordinate` object to alter the UTM conversion as required.

```C#
//Ellipsoid is set on the Coordinate object for UTM/MGRS
c.Set_Datum(6378137, 298.257222101);
//OR
c.Set_Datum(Earth_Ellipsoid_Spec.GRS80_1979);
```

I recommend you check out the [Developer Guide's UTM/MGRS](https://coordinatesharp.com/DeveloperGuide#universal-transverse-mercator-and-military-grid-reference-system) section for more info.

Let me know if that answers your questions, if you have any follow ups, or I am not understanding correctly.
