### ISSUE TITLE
How to move a coordinate?

### ISSUE THREAD

**Issue by beppe9000** [Tronald/CoordinateSharp#31]
I was thinking of using the line equation to move torwards another coordinate in the cartesian format.
But I read on the readme page that the cartesian projection is not very accurate.

Is there a way to do that with normal coordinates?

**Comment by Tronald** [comment]
Thanks for reaching out and checking our CoordinateSharp.

The Cartesian format just assumes a spherical earth, which may or may not be suitable for your purposes. It's not "not" accurate, it's just not the most accurate. It really just depends on what you are trying to achieve and how accurate you need the results to be. 

If you are converting so that you can move your coordinate lets say, 35 KM @ 230 degrees, you will probably be ok converting to Cartesian and then converting back. The Haversine formula for distance calculation does this and it works well. I wouldn't launch a rocket that requires hyper-accuracy on spherical earth calculations, but for general purpose it's normally ok. You will need to do some tests to determine if the results are accurate enough for you. 

Could you give me a better idea of what you are trying to execute. This sounds like it may be a good feature addition to add that I hadn't thought of.

**Comment by Tronald** [comment]
I thought about this a bit and decided this feature needs to be in the library. I'm going to add a "move" function that takes into account the earth shape. You may get slightly better results then doing strait sphere calcs from Cartesian. I researched it and it seems like a simple add-on. I'm going to look  into adding Vincenty's formulae option to the distance calculator as well for increased accuracy. I will keep you posted. I will work on this today. If it proves as simple as I think, I will push a package tonight or tomorrow.

[Reference](https://gis.stackexchange.com/questions/5821/calculating-latitude-longitude-x-miles-from-point)

**Comment by Tronald** [comment]
The feature has been added, but I need to run some tests when able before releasing. I may expand my eclipse tables as well. If you want to play around with it before release you can grab the files in the [Vincenty Branch](https://github.com/Tronald/CoordinateSharp/tree/Vincenty_Distance_Enhancements). 

To move the coordinate as described, you pass distance in meters, bearing and an earth shape. Example

```C#
coordinate.Move(34789, 270, Shape.Ellipsoid);
```

The documentation in the branch explains it a bit more. I will keep the issue open until I publish the update. Thanks for the idea, this was fun to make!

**Comment by beppe9000** [comment]
Well, I was late in replying due to social life, but I actually had a pic ready to describe my idea. 
You pretty much nailed it, I will check the code as soon as I can.
So the conversion to Cartesian was not required, good!

![javaw_2018-05-30_21-36-26](https://user-images.githubusercontent.com/6625123/40743498-fae90918-6451-11e8-8c30-3550b26360e6.png)

Ps. Did you consider an overload that takes another coordinate as argument instead of a bearing?
Something like `coordinate.Move(target, meters)` feels awesome (and very natural).

**Comment by Tronald** [comment]
Ahhh I see, great idea! It shouldn’t be too hard to implement. I just need to grab the bearing to the target and then call the original Move function. I’ll make sure I get that in there before release. I’ll keep you posted.

**Comment by Tronald** [comment]
I just released the update (1.1.2.6). It may take a bit to show up on Nuget. Let me know if you run into any issues.

Thanks again.

**Comment by beppe9000** [comment]
Thanks to you! I will post if I get any problem about that.
