### ISSUE TITLE
Coordinate.TryParse() will not accept coordinate without a hemisphere

### ISSUE THREAD

**Issue by FanciestW** [Tronald/CoordinateSharp#63]
A coordinate in degree minute second or degree decimal minutes will not be accepted if they do not have a hemisphere value (N, S, E, W). For example a TryParse with latitude as the passed type with "12 12.123" as the coordinate string will not be parsed correctly. That should be parsed to return a double degree value of 12.20205.

**Comment by Tronald** [comment]
Thanks for the suggestion. I’ll add logic to handle this in the signed degree parser logic.

Splitting DD into DDM or DMS without position indicators seems uncommon for lat/long. Are you seeing this occurring?

**Comment by Tronald** [comment]
It’s done. 

I unfortunately don’t have WiFi for my laptop, so I’ll make the commit when able. Good suggestion I like it. 

Just a heads up, I’m writing a test project to add to the solution to help automate tests. I need it due to the rate the library is growing. I don’t plan to release the next update until it is complete. It just proved useful writing the parsers though! Hopefully next week I’ll push the update.

**Comment by Tronald** [comment]
@FanciestW [HERE](https://github.com/Tronald/CoordinateSharp/blob/v1.1.3.8/CoordinateSharp%20v1_1_3_8%20(ALPHA).zip) is an updated compiled version of 1.1.3.8 (still in works). 

It should parse as suggested. Keep bring any issues like this to my attention as you find them. 

Thanks Again.
