### ISSUE TITLE
Inserting seconds for N & W coordinates

### ISSUE THREAD

**Issue by dddns** [Tronald/CoordinateSharp#76]
Howdy,
I just found your project and it's fantastic!

But, when i try to insert a UTM/WGS84 coordinate, the seconds part, I'll insert 27.03 as second and will tell me that i Can't.
Am i doing something wrong or is it a bug?

==
 Dim c As New CoordinateSharp.Coordinate
        c.Latitude = New CoordinateSharp.CoordinatePart(txtwgs84_nd.Text, txtwgs84_nm.Text, txtwgs84_ns.Text, CoordinateSharp.CoordinatesPosition.N, c)
        c.Longitude = New CoordinateSharp.CoordinatePart(txtwgs84_wd.Text, txtwgs84_wm.Text, txtwgs84_ws.Text, CoordinateSharp.CoordinatesPosition.W, c)

        c.GeoDate = New DateTime(2019, 1, 5, 11, 56, 0)

        MsgBox(c.Latitude.DecimalDegree & " - " & c.Longitude.DecimalDegree)
==

Thanks in advanced,

**Comment by dddns** [comment]
Forgot to post the error:

System.ArgumentOutOfRangeException: Seconds cannot be greater than or equal to 60.
Parameter name: Seconds out of range
   at CoordinateSharp.CoordinatePart..ctor(Int32 deg, Int32 min, Double sec, CoordinatesPosition pos, Coordinate c)

**Comment by dddns** [comment]
Hi Tronald,
I thank you, your object is fantastic!

Well i believe it's WGS84, it's this:

40° 23′ 26.12″ N 003° 40′ 37.21″ W

the values in each textbox are as the bellow example:

txtwgs84_nd.text = 40
txtwgs84_nm.text = 23
txtwgs84_ns.text = 26.12

txtwgs84_wd.text = 3
txtwgs84_wm.text = 40
txtwgs84_ws.text = 37.21

Am i doing something wrong?

**Comment by Tronald** [comment]
Ok Great Thanks. That's a Geodetic (Lat/Long) coordinate. So your code should work in theory, so lets see if we can figure out what is happening. 

1. Are you using version 1.1.4.1 and if so how did you get the package (Nuget, GitHub, Downloaded from the Website)?

2. Check out this [VB.net Fiddle](https://dotnetfiddle.net/BRf7ju) and run it. Compare it to your code to make sure it matches as we may be missing something, because it should work.

3. You are using the secondary method to build your Coordinate. `Coordinate.TryParse()` may be easier for you as you can just pass your whole Coordinate `string` into it. [Here is a Fiddle](https://dotnetfiddle.net/rai1bS)

Let me know what your find or what other questions you have.

**Comment by dddns** [comment]
http://jorge.albergaria.pt/files/testegps.zip

Grr can't attach files,

**Comment by Tronald** [comment]
That's interesting that even `convert.todouble()` fails as that is standard .NET code. The `CoordinatePart` only accepts `double` values, so if the .NET framework is having issues with your region, it is not something I would be able to fix. 

I unfortunately can't view your project right now, but I will check it later when I get home. I'm going to close the issue, but I will respond here if I find any suggestions for you.

**Comment by dddns** [comment]
Thanks, you're fantastic :)

**Comment by Tronald** [comment]
Hi @dddns I finally had a chance to look at your project and yes the comma in your seconds value is definitely the issue as the .NET framework doesn't recognize that as a valid double. In your current culture, is it normal to use commas instead of decimals points for a number? 

If you are worried about people using commas, I would maybe just restrict the input of your text box to only allow numbers and periods OR maybe replace any commas in the string with a period.

```C#
 txtwgs84_ns.Text.Replace(",",".")
```

Best of luck and let me know if you need anymore help!

-Justin

**Comment by dddns** [comment]
Hi Tronald,
Thanks, that's what i'm doing, i'm replacing the comma for dot, it's bullet prof now!!
I just reported to you to make your .dll even better, you could, if a comma comes in the second part, replace it with the period.

My regional settings is pt_PT which for number is:

1.123,00

point for group digit, and comma for decimal part,
Best regards and your .dll is fantastic!
