### ISSUE TITLE
1.1.4.3 Some EagerLoadType enums still not working in EagerLoad constructor

### ISSUE THREAD

**Issue by parkerdj98** [Tronald/CoordinateSharp#83]
Some of the EagerLoadType enums are still not working correctly in the 1.1.4.3 version of the EagerLoad() constructor, in particular these combinations are failing:

failed: EagerLoad(EagerLoadType.Cartesian)
failed: EagerLoad(EagerLoadType.Celestial)
failed: EagerLoad(EagerLoadType.Cartesian | EagerLoadType.Celestial)

They are incorrectly setting the UTM_MGRS property to true instead of false.

**Comment by Tronald** [comment]
My Apologies.

This ended up being less simple than I thought. What framework / version of core are you using?

There ended up being 2 issues occurring and my last fix only fixed one of them. The second issue had to do with the EagerLoadType Flags themselves. For whatever reason the logic would only work in some environments, which is why I missed the issue on my end. It looks like certain environments weren't assigning int values to the flags which was causing the flag constructor to not work properly. It looks like I can fix by assigning an numerical value to each flag.

I'll publish another package here shortly

**Comment by Tronald** [comment]
Thank you for your patience and letting me know the issue was still present. I tried it in a few environments and it seems to be working all around now. [Fiddle Confirms](https://dotnetfiddle.net/tkhkUX)

Download 1.1.4.4. from Nuget and get back to me with results if you don't mind :)

**Comment by parkerdj98** [comment]
Good news - I downloaded 1.1.4.4 and the EagerLoad() constructor now works correctly with all combinations of the EagerLoadType enum!  Thanks for fixing this issue so quickly, it was very much appreciated.

BTW, I am using the .NET Framework 4.0 version.  We are using your CoordinateSharp library in a Coast Guard Mission Management application, mainly to do conversions of latitude/longitude locations to UTM.  We are very happy with it!
