### ISSUE TITLE
sunset is nullable and never sets in Oklahoma?

### ISSUE THREAD

**Issue by rfnoise** [Tronald/CoordinateSharp#85]
I realize that the sunset and sunrise are nullable and there are real situations for this (e.g. Alaska).

However, please try this:

            Coordinate c = new Coordinate(33.87515, -95.96789, new DateTime(2019, 2, 6, 1, 39, 22));
            Console.WriteLine(c.CelestialInfo.SunCondition);

Sunset is nullable. Suncondition is NoSet. However, look where the coordinates are:

https://www.google.com/maps/place/33%C2%B052'30.5%22N+95%C2%B058'04.4%22W/@33.5441522,-98.1716845,7.42z/data=!4m5!3m4!1s0x0:0x0!8m2!3d33.87515!4d-95.96789

Last i checked, the sun does set in Oklahoma every day all year around?

Am i doing something wrong or making some assumptions that i shouldn't here?
thanks

**Comment by Tronald** [comment]
Thank you checking out CoordinateSharp and for reaching out. 

The reason you are seeing this is because the library operates in UTC Time, regardless of if you pass a local time. Any `DateTime` passed through the constructor is though to be in UTC. The SunSet for 06-Feb-19 at those coordinates doesn't actually occur during the day when operating in UTC time. If converted to local time however, you will see a sunset.


````C#
//Add 6 hours to your constructor to convert to UTC
Coordinate c = new Coordinate(33.87515, -95.96789, new DateTime(2019, 2, 6, 7, 39, 22));

//Local offset is -6 for Oklahoma
Celestial cel = Celestial.Celestial_LocalTime(c, -6);

Console.WriteLine(cel.SunSet); // 6:00:11 PM SUNSET
````

If you haven't had a chance to check it out yet, the [Developer Guide](http://coordinatesharp.com/DeveloperGuide) has a lot of good info. 

Let me know if you need anymore help!

-Justin

**Comment by rfnoise** [comment]
Interesting, the time I passed was a UTC and represents the timestamp of the satellite image. Since the satellite covers a big portion of the earth, I have no easy way to determine local timezones for the coordinate. I was hoping things would all work with UTC.

 

Joe

**Comment by Tronald** [comment]
If you're already operating in UTC then there is a simple solution thankfully! You just need to add some `SunCondition` logic for when the sunset returns null.

If the `SunCondition` returns `NoSet` your program is safe to assume the sun is up and good to save the satellite image. This same is true if the `SunCondtion` returns `UpAllDay`. Where you would need to be concerned is if the `SunCondition` returns either `DownAllDay` or `NoRise`

Example:

```C#
Coordinate c = new Coordinate(33.87515, -95.96789, new DateTime(2019, 2, 6, 1, 39, 22));
switch(c.CelestialInfo.SunCondition)
{
	case CelestialStatus.UpAllDay:
		//Save Image
		break;
	case CelestialStatus.DownAllDay:
		//DON'T Save Image
		break;
	case CelestialStatus.NoSet:
		//Save Image
		break;
	case CelestialStatus.NoRise:
		//DON'T Save Image
		break;
	case CelestialStatus.RiseAndSet:
		//USE YOUR EXISTING LOGIC TO DETERMINE IF THE IMAGE WAS BEFORE OR AFTER SUNSET 
		break;
        default:
                //Save Image
                break;
}
````
I notice this longitudinal region of the earth often causes problems. The days start getting longer and they fall into that "there might not be a UTC sunset for a day" season as the sun cycle extends. The library is designed to only return events for the exact day specified, which can cause issues like you're seeing on occasion.

Hopefully with the `SunConditions` you can get it to work how you need! Let me know if you would like further explanation and I would be glad to help!

-Justin

**Comment by rfnoise** [comment]
Justin

 

Nope, that doesn’t work. The image was taken at 8pm local time (correcting the UTC time for -6 offset), clearly the sun is not up. But the reported sun condition is NoSet. So this would result in a dark image being saved.

I’m still trying a few things to narrow the issue. 

Thanks

Joe

**Comment by Tronald** [comment]
My apologies, my above logic is flawed as it doesn't account for pre-sunrise events. For example, if the condition is `NoSet` you need to determine if SunRise has occurred first.  So If operating in UTC.


```C#
Coordinate c = new Coordinate(33.87515, -95.96789, new DateTime(2019, 2, 6, 1, 39, 22));
switch(c.CelestialInfo.SunCondition)
{
	case CelestialStatus.UpAllDay:
		//Save Image
		break;
	case CelestialStatus.DownAllDay:
		//DON'T Save Image
		break;
	case CelestialStatus.NoSet:
		//IF SUNRISE HAS OCCURED - Save Image*************
		break;
	case CelestialStatus.NoRise:
		//IF SUNSET HAS NOT OCCURED - Save Image************
		break;
	case CelestialStatus.RiseAndSet:
		//USE YOUR EXISTING LOGIC TO DETERMINE IF THE IMAGE WAS BEFORE OR AFTER SUNSET 
		break;
        default:
                //Save Image
                break;
}
```

**Comment by Tronald** [comment]
@rfnoise sorry to keep bugging you. I plan to release 1.1.4.5 this weekend. I am trying to add the functions `IsSunUp()` and `IsMoonUp()` that you can call. They will return a bool value and should eliminate the need for the above logic entirely. I believe such a feature would be useful for this library.

**Comment by rfnoise** [comment]
Thanks for following up. 

 

I ended up converting to local time by calculating offset at target coordinates and then sunrise / sunset seem to work just fine. I do use the logic you suggested as well in case the sun never comes up or never goes down. It all seems to be working now.

 

However, If there was an IsSunUp(), I would just use that 😊

 

thanks

Joe

**Comment by Tronald** [comment]
The feature is added, but unfortunately, Microsoft in their infinite wisdom locked me out of my Nuget account for 30 days after I changed my phone number. It would have been nice to know that would happen BEFORE I changed my number. I'm trying to get it unlocked, but I am at the mercy of Microsoft support so I don't expect much expedient help.

Because of that I am not going to "release" yet, but I still put the compiled library on the website if you want to check it out early. Your call.

If you decide to download, I can remind you when the Nuget package for the version goes out if you want so that you can switch back.

[Library can be downloaded here](http://coordinatesharp.com/Files/CoordinateSharp%20v1_1_4_5.zip).

Example use:

```C#
Coordinate c = new Coordinate(25, 25, new DateTime(2019, 2, 6, 13, 14, 1));
bool isSunUp = c.CelestialInfo.IsSunUp;
```

Sun and Moon "IsUp" is calculated from `Coordinate.GeoDate` this works in both UTC and Local (if you converted to local using the steps I provided previously'.

I really like this feature being in the library, so thank you for raising the issue and helping me come to this idea. Hopefully it helps.

**Comment by rfnoise** [comment]
Thanks, Justin. This sounds great. I will wait for Nuget release, mainly because I am lazy. But I do get notifications when there is updates and will do so when it’s available. I really appreciate your library, it really makes for some neat features without having to dive into the complexities. Thanks!
