### ISSUE TITLE
new output Property - Distance to the Moon

### ISSUE THREAD

**Issue by wider2** [Tronald/CoordinateSharp#9]
Good evening
I just want to say thank you for you Celestial c# application
It is interesting to test it

Can I ask just one thing to add
inside Celestial.MoonCalculations.cs
we can see the nice class MoonPosition with property Distance 

is it possible to add new property to output - calculated distance from Earth to Moon?
when application provide output in such way
**double distance = c.CelestialInfo.MoonDistance;**
to know when will be the perigee and apogee day

**Comment by Tronald** [comment]
Thank you for your feedback, I'm glad somebody is using this. I'm sorry for the delayed response as I have been away. 

I think such an output property would be a good addition to this library. I'm hoping it's as easy as exposing that distance value you had mentioned. I may be able to indicate whether perigee or apogee has been reached as well with another property.

I will investigate and get back to you.

**Comment by Tronald** [comment]
It looks like the moon distance formula contained in this library has a standard deviation of 3388 km with a max of 7645 km calculated between the years 1950-2050. The distance deviation shouldn't be much of a factor if one is trying to determine perigee and apogee days only. If one is trying to determine distance however, it should be noted that the precision of this formula may not be sufficient enough for all uses. 

I will create a property so that the information is accessible, but will annotate the limitation in the documentation so that the user may make a determination as to whether this functionality can fulfill their purposes.

The moon distance formula contained in this library was provided by Dr. Louis Strous, an astronomer and physicist who is now a software developer out of the Netherlands. The formulas can be found here.

http://aa.quae.nl/en/reken/hemelpositie.html#1_3

I will also give him proper credit in the documentation for these formulas as credit is currently given to another developer who used Dr. Strouses formula.

**Comment by wider2** [comment]
thank you for response.
Your library is good enough. My idea could be quite strange or mad, but I intend to do it more practical way. Idea is to make output of your library more wider:

1. distance to the moon
	return double value

2. Significant dates: library check the current or given DateTime and return name of the day

by example, 
26nov2017 Moon will be at first quarter
3dec2017 will be the Full Moon
and 4.12.2017 will be the Super Moon.

	or standard date of 4 Equinox, by simplified example
            string dateName = "";
            if (dt.Month == 3 && dt.Day == 20) dateName = "Vernal Equinox";
            if (dt.Month == 6 && dt.Day == 21) dateName = "Summer Solstice";
            if (dt.Month == 9 && dt.Day == 22) dateName = "Autumnal Equinox";
            if (dt.Month == 12 && dt.Day == 21) dateName = "Winter Solstice";

or any other remarkable astronomy dates appear...

3. Define Zodiac sign
http://jivebay.com/calculating-the-moon-phase-part-2/
this sample demonstrate idea how to get current Zodiac sign
 according to current moon's ecliptic latitude and longitude

**Comment by Tronald** [comment]
I like it lets do it!

I have added the MoonDistance property. It is currently in the MoonDistance branch. I want to test it a bit further to get a better gauge on it's accuracy. Once I am comfortable with it I will merge it to the Master.

I'm going to mark this issue closed.

**Comment by wider2** [comment]
all right
what about my other ideas?

**Comment by Tronald** [comment]
I have opened a new issue for the above features and will push them with 1.1.1.6. If you wish to be assigned  this issue with me, comment on it and I will add you :)

**Comment by Tronald** [comment]
I guess I can't assign a contributor if they aren't the originator of the issue. Anyway, I plan to work on it. Keep pushing any ideas, code or suggestions my way.
